// <auto-generated />
using System;
using HidroSense.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HidroSense.Migrations
{
    [DbContext(typeof(HidroSenseContext))]
    [Migration("20250630034328_AgregarNivelYToken")]
    partial class AgregarNivelYToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HidroSense.Models.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFuente")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdFuente");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("HidroSense.Models.FuenteAgua", b =>
                {
                    b.Property<int>("IdFuente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuente"));

                    b.Property<decimal>("Altitud")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreFuente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoFuente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFuente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("FuentesAgua");
                });

            modelBuilder.Entity("HidroSense.Models.Medicion", b =>
                {
                    b.Property<int>("IdMedicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicion"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFuente")
                        .HasColumnType("int");

                    b.Property<float?>("NivelTurbidez")
                        .HasColumnType("real");

                    b.Property<float?>("Ph")
                        .HasColumnType("real");

                    b.Property<float?>("Temperatura")
                        .HasColumnType("real");

                    b.HasKey("IdMedicion");

                    b.HasIndex("IdFuente");

                    b.ToTable("Mediciones");
                });

            modelBuilder.Entity("HidroSense.Models.ResultadoTratamiento", b =>
                {
                    b.Property<int>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResultado"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTratamiento")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("PhFinal")
                        .HasColumnType("real");

                    b.Property<float?>("TemperaturaFinal")
                        .HasColumnType("real");

                    b.Property<float?>("TurbidezFinal")
                        .HasColumnType("real");

                    b.HasKey("IdResultado");

                    b.HasIndex("IdTratamiento");

                    b.ToTable("ResultadosTratamiento");
                });

            modelBuilder.Entity("HidroSense.Models.SistemaPurificacion", b =>
                {
                    b.Property<int>("IdSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSistema"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSistema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSistema");

                    b.ToTable("SistemasPurificacion");
                });

            modelBuilder.Entity("HidroSense.Models.TratamientoAplicado", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTratamiento"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFuente")
                        .HasColumnType("int");

                    b.Property<int>("IdSistema")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTratamiento");

                    b.HasIndex("IdFuente");

                    b.HasIndex("IdSistema");

                    b.ToTable("TratamientosAplicados");
                });

            modelBuilder.Entity("HidroSense.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HidroSense.Models.Alerta", b =>
                {
                    b.HasOne("HidroSense.Models.FuenteAgua", "FuenteAgua")
                        .WithMany()
                        .HasForeignKey("IdFuente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuenteAgua");
                });

            modelBuilder.Entity("HidroSense.Models.FuenteAgua", b =>
                {
                    b.HasOne("HidroSense.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HidroSense.Models.Medicion", b =>
                {
                    b.HasOne("HidroSense.Models.FuenteAgua", "FuenteAgua")
                        .WithMany()
                        .HasForeignKey("IdFuente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuenteAgua");
                });

            modelBuilder.Entity("HidroSense.Models.ResultadoTratamiento", b =>
                {
                    b.HasOne("HidroSense.Models.TratamientoAplicado", "TratamientoAplicado")
                        .WithMany()
                        .HasForeignKey("IdTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TratamientoAplicado");
                });

            modelBuilder.Entity("HidroSense.Models.TratamientoAplicado", b =>
                {
                    b.HasOne("HidroSense.Models.FuenteAgua", "FuenteAgua")
                        .WithMany()
                        .HasForeignKey("IdFuente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HidroSense.Models.SistemaPurificacion", "SistemaPurificacion")
                        .WithMany()
                        .HasForeignKey("IdSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuenteAgua");

                    b.Navigation("SistemaPurificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
